name: PropHuntPlugin
main: fr.pixfri.prophunt.PropHunt
version: 1.0+1.20.6
api-version: 1.20
author: Pixfri
website: https://pixfri.github.io/
commands:
  broadcast:
    aliases:
      - bc
    description: Send a message to the whole server
    usage: /[broadcast/bc] <message>